import assert from "node:assert/strict";
import test from "node:test";
import { LIST_COLUMNS, assignedColumns, recordGroups } from "./incidentRecord.ts";

const STORED_COLUMNS = [
  "incident_number",
  "incident_types",
  "reported_date",
  "nearest_populated_centre",
  "province",
  "company",
  "status",
  "latitude",
  "longitude",
  "approximate_volume_released_m3",
  "substance",
  "release_type",
  "significant",
  "year",
  "occurrence_date_and_time",
  "discovered_date_and_time",
  "detailed_what_happened",
  "what_happened_category",
  "detailed_why_it_happened",
  "why_it_happened_category",
  "duration_of_interruption_of_pipeline_operations",
  "pipeline_or_facility_type",
  "activity_being_performed_at_time_of_incident",
  "how_the_incident_was_discovered",
  "closed_date",
  "pipeline_or_facility_equipment_involved",
  "rupture",
  "incident_type",
  "released_substance_type",
  "released_volume_m3",
  "pipe_body_release",
  "residual_effects_on_the_environment",
  "source_of_explosion",
  "source_of_fire",
  "activity_at_time_of_fatality",
  "number_of_fatalities",
  "type_of_injury",
  "number_of_individuals_injured",
  "workdays_lost",
  "work_restricted_by_injury",
  "conditions_that_resulted_in_the_operation_beyond_limits",
  "conditions_that_resulted_in_adverse_effects_on_the_environment",
  "number_of_people_evacuated",
  "regulation",
  "pipeline_name",
  "pipeline_outside_diameter_nps",
  "pipeline_length_km",
  "substance_carried",
  "facility_name",
  "facility_type",
  "facility_latitude",
  "facility_longitude",
  "country",
  "affects_company_property",
  "off_company_property",
  "affects_pipeline_right_of_way",
  "affects_off_pipeline_right_of_way",
  "land_use",
  "population_density",
  "kilometre_post",
  "emergency_level",
  "investigation_type",
  "was_neb_staff_deployed",
  "related_neb_event_number",
  "equipment_or_component_involved",
  "design_standard",
  "nominal_pipe_size",
  "material",
  "material_grade",
  "schedule",
  "design_wall_thickness_mm",
  "custom_design_wall_thickness_mm",
  "actual_wall_thickness_mm",
  "licensed_maximum_operating_pressure_kpa",
  "restricted_operating_pressure_kpa",
  "actual_operating_pressure_at_time_of_failure_kpa",
  "designed_depth_of_cover_m",
  "actual_depth_of_cover_m",
  "year_of_manufacture",
  "year_of_installation",
  "year_when_put_into_service",
  "most_recent_cathodic_protection_reading_at_incident_site_mv_vs_cu_cuso4",
  "weld_type",
  "seam_type",
  "seam_joining_method",
  "seam_clock_position",
  "coating_location",
  "coating_type",
  "coating_condition",
  "application_method",
  "year_when_the_coating_was_applied",
  "insulation_installed",
  "repair_type",
  "repair_date",
  "equipment_or_component_has_never_been_inspected",
  "most_recent_inspection_date_for_the_failed_equipment_or_component",
  "type_of_most_recent_inspection",
  "most_recent_inspection_part_of_the_routine_inspection_program",
  "no_maintenance_done_on_this_equipment_or_component",
  "date_of_the_most_recent_maintenance_work_for_the_failed_equipment_or_component",
  "most_recent_maintenance_type",
  "most_recent_maintenance_work_part_of_the_routine_maintenance_program",
  "loaded_at",
  "likelihood",
  "consequence",
  "risk",
  "boscem_cost",
  "boscem_level",
  "consequence_base",
  "elevated_density",
  "category_step",
  "recency",
  "n",
  "nearby",
  "never_inspected_factor",
  "scores_scored_at",
  "criticality_score",
  "criticality_reasoning",
  "threat_category",
  "criticality_confidence",
  "criticality_status",
  "criticality_scored_at",
  "groundwater_impact_score",
  "groundwater_reasoning",
  "groundwater_confidence",
  "groundwater_status",
  "avi_index",
  "avi_status",
  "groundwater_scored_at",
];

test("record groups omit blanks and keep zero and false", () => {
  const groups = recordGroups({
    incident_number: "A-1",
    company: "Pipe Co",
    province: " ",
    detailed_what_happened: "",
    likelihood: 4,
    consequence: null,
    never_inspected_factor: 0,
    elevated_density: false,
    criticality_reasoning: "wall loss",
  });
  const fields = groups.flatMap((group) => group.fields.map((field) => [field.column, field.value]));
  assert.deepEqual(fields, [
    ["incident_number", "A-1"],
    ["company", "Pipe Co"],
    ["likelihood", "4"],
    ["elevated_density", "No"],
    ["never_inspected_factor", "0"],
    ["criticality_reasoning", "wall loss"],
  ]);
  assert.equal(groups.some((group) => group.fields.length === 0), false);
});

test("every stored column is assigned once and the list is a subset", () => {
  const assigned = assignedColumns();
  assert.equal(new Set(assigned).size, assigned.length);
  assert.deepEqual([...assigned].sort(), [...STORED_COLUMNS].sort());
  for (const column of LIST_COLUMNS) {
    assert.equal(assigned.includes(column), true);
  }
});
